name: "Publish Docker image"
on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_2 }}
          password: ${{ secrets.DOCKER_SECRET_2 }}

      # set env TAGNAME to latest if master
      - name: Set env TAGNAME
        if: github.ref == 'refs/heads/master'
        run: echo "TAGNAME=latest" >> $GITHUB_ENV

      # create env name with git branch if not master
      - name: Set env TAGNAME
        if: ${{ github.ref != 'refs/heads/master' }}
        run: echo "TAGNAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: scienceis/uoa-inzight-lite:${{ env.TAGNAME }}
